"""The `package:test` runner that `dart_test` runs a test through.

`dart_test` compiles a test at build time and runs it under `package:test`'s own
runner, because that runner is what implements the protocols Bazel asks a test
framework to honour: `--test_filter`, sharding, and a per-case result report.
Run directly, a test file gets none of them, and `package:test` applies a
hard-coded 30-second timeout per case besides — a second authority over time
that Bazel's `size`/`timeout` already owns.

The runner and the test must come from the same `package:test`: they talk over
a protocol private to that package's version, so a runner pinned by rules_dart
would drift from the version a user's lockfile resolves. The runner is therefore
built from the user's own `package:test`, once per version, inside the spoke
repository that provides it: the spoke's public `test` target is a
`dart_test_package` that forwards the library unchanged and carries the runner
beside it, and `dart_test` finds the runner on whichever direct dependency is
`package:test`.
"""

load("//dart:providers.bzl", "DartInfo")

DartTestRunnerInfo = provider(
    doc = "The `package:test` runner built from a `package:test` library.",
    fields = {
        "runner": "File: the runner, compiled to a kernel (`.dill`).",
    },
)

# The runner's entrypoint is `package:test`'s own `bin/test.dart`, which does
# nothing but re-export this library. `bin/` is not part of a pub spoke, which
# stages `lib/` only, so the one line is written here instead.
_RUNNER_MAIN = """\
// Generated by rules_dart: the `package:test` runner, as `dart test` runs it.
export 'package:test/src/executable.dart';
"""

def _dart_test_runner_main_impl(ctx):
    out = ctx.actions.declare_file(ctx.label.name + ".dart")
    ctx.actions.write(output = out, content = _RUNNER_MAIN)
    return [DefaultInfo(files = depset([out]))]

dart_test_runner_main = rule(
    implementation = _dart_test_runner_main_impl,
    doc = "Writes the entrypoint the `package:test` runner is compiled from.",
)

def _dart_test_package_impl(ctx):
    library = ctx.attr.library
    runner = [f for f in ctx.attr.runner[DefaultInfo].files.to_list() if f.extension == "dill"]
    if len(runner) != 1:
        fail("%s: `runner` must produce exactly one `.dill`, got %s" % (ctx.label, runner))
    return [
        library[DefaultInfo],
        library[DartInfo],
        DartTestRunnerInfo(runner = runner[0]),
    ]

dart_test_package = rule(
    implementation = _dart_test_package_impl,
    attrs = {
        "library": attr.label(
            doc = "The `package:test` `dart_library`.",
            mandatory = True,
            providers = [DartInfo],
        ),
        "runner": attr.label(
            doc = "A kernel-mode `dart_binary` built from `library`.",
            mandatory = True,
        ),
    },
    doc = "`package:test` as a dependency, carrying the runner built from it.",
)
