"""Create a repository to hold the toolchains

This follows guidance here:
https://docs.bazel.build/versions/main/skylark/deploying.html#registering-toolchains
"
Note that in order to resolve toolchains in the analysis phase
Bazel needs to analyze all toolchain targets that are registered.
Bazel will not need to analyze all targets referenced by toolchain.toolchain attribute.
If in order to register toolchains you need to perform complex computation in the repository,
consider splitting the repository with toolchain targets
from the repository with <LANG>_toolchain targets.
Former will be always fetched,
and the latter will only be fetched when user actually needs to build <LANG> code.
"
The "complex computation" in our case is simply downloading large artifacts.
This guidance tells us how to avoid that: we put the toolchain targets in the alias repository
with only the toolchain attribute pointing into the platform-specific repositories.
"""

# Dart SDK platform strings as used in the download URL:
# https://storage.googleapis.com/dart-archive/channels/stable/release/{version}/sdk/dartsdk-{platform}-release.zip
PLATFORMS = {
    "macos-arm64": struct(
        compatible_with = [
            "@platforms//os:macos",
            "@platforms//cpu:aarch64",
        ],
        dart_os = "macos",
        dart_arch = "arm64",
    ),
    "macos-x64": struct(
        compatible_with = [
            "@platforms//os:macos",
            "@platforms//cpu:x86_64",
        ],
        dart_os = "macos",
        dart_arch = "x64",
    ),
    "linux-x64": struct(
        compatible_with = [
            "@platforms//os:linux",
            "@platforms//cpu:x86_64",
        ],
        dart_os = "linux",
        dart_arch = "x64",
    ),
    "linux-arm64": struct(
        compatible_with = [
            "@platforms//os:linux",
            "@platforms//cpu:aarch64",
        ],
        dart_os = "linux",
        dart_arch = "arm64",
    ),
    "windows-x64": struct(
        compatible_with = [
            "@platforms//os:windows",
            "@platforms//cpu:x86_64",
        ],
        dart_os = "windows",
        dart_arch = "x64",
    ),
}

# Known-working cross-compilation pairs: exec platform -> list of target platforms.
# Dart's AOT compiler can cross-compile exe and aot-snapshot to these targets
# using --target-os and --target-arch flags.
CROSS_TARGETS = {
    "macos-arm64": ["linux-x64", "linux-arm64"],
    "macos-x64": ["linux-x64", "linux-arm64"],
    "linux-x64": ["linux-arm64"],
    "linux-arm64": ["linux-x64"],
    "windows-x64": ["linux-x64", "linux-arm64"],
}

def _toolchains_repo_impl(repository_ctx):
    build_content = """# Generated by toolchains_repo.bzl
#
# These can be registered via register_toolchains() or passed to --extra_toolchains flag.
# By default all these toolchains are registered by the dart_register_toolchains macro
# so you don't normally need to interact with these targets.

"""

    # Native toolchains: exec and target constraints match the same platform.
    for [platform, meta] in PLATFORMS.items():
        build_content += """
toolchain(
    name = "{platform}_toolchain",
    exec_compatible_with = {compatible_with},
    target_compatible_with = {compatible_with},
    toolchain = "@{user_repository_name}_{platform}//:dart_toolchain",
    toolchain_type = "@rules_dart//dart:toolchain_type",
)
""".format(
            platform = platform,
            user_repository_name = repository_ctx.attr.user_repository_name,
            compatible_with = meta.compatible_with,
        )

    # Cross-compilation toolchains: exec constraints = host, target constraints = cross target.
    for [exec_platform, targets] in CROSS_TARGETS.items():
        exec_meta = PLATFORMS[exec_platform]
        for target_platform in targets:
            target_meta = PLATFORMS[target_platform]
            cross_name = exec_platform + "_cross_" + target_platform
            build_content += """
toolchain(
    name = "{cross_name}_toolchain",
    exec_compatible_with = {exec_compatible_with},
    target_compatible_with = {target_compatible_with},
    toolchain = "@{user_repository_name}_{exec_platform}//:dart_toolchain_cross_{target_platform}",
    toolchain_type = "@rules_dart//dart:toolchain_type",
)
""".format(
                cross_name = cross_name,
                exec_compatible_with = exec_meta.compatible_with,
                target_compatible_with = target_meta.compatible_with,
                user_repository_name = repository_ctx.attr.user_repository_name,
                exec_platform = exec_platform,
                target_platform = target_platform,
            )

    repository_ctx.file("BUILD.bazel", build_content)

toolchains_repo = repository_rule(
    _toolchains_repo_impl,
    doc = """Creates a repository with toolchain definitions for all known platforms
     which can be registered or selected.""",
    attrs = {
        "user_repository_name": attr.string(doc = "what the user chose for the base name"),
    },
)
