"""Declare runtime dependencies

These are needed for local dev, and users must install them as well.
See https://docs.bazel.build/versions/main/skylark/deploying.html#dependencies
"""

load("@bazel_tools//tools/build_defs/repo:http.bzl", _http_archive = "http_archive")
load("@bazel_tools//tools/build_defs/repo:utils.bzl", "maybe")
load("//dart/private:toolchains_repo.bzl", "PLATFORMS", "toolchains_repo")
load("//dart/private:versions.bzl", "TOOL_VERSIONS")

def http_archive(name, **kwargs):
    maybe(_http_archive, name = name, **kwargs)

# WARNING: any changes in this function may be BREAKING CHANGES for users
# because we'll fetch a dependency which may be different from one that
# they were previously fetching later in their WORKSPACE setup, and now
# ours took precedence. Such breakages are challenging for users, so any
# changes in this function should be marked as BREAKING in the commit message
# and released only in semver majors.
# This is all fixed by bzlmod, so we just tolerate it for now.
def rules_dart_dependencies():
    # The minimal version of bazel_skylib we require
    http_archive(
        name = "bazel_skylib",
        sha256 = "6e78f0e57de26801f6f564fa7c4a48dc8b36873e416257a92bbb0937eeac8446",
        urls = [
            "https://github.com/bazelbuild/bazel-skylib/releases/download/1.8.2/bazel-skylib-1.8.2.tar.gz",
            "https://mirror.bazel.build/github.com/bazelbuild/bazel-skylib/releases/download/1.8.2/bazel-skylib-1.8.2.tar.gz",
        ],
    )

########
# Remaining content of the file is only used to support toolchains.
########
_DOC = "Fetch the Dart SDK for a given version and platform"
_ATTRS = {
    "dart_version": attr.string(mandatory = True, values = TOOL_VERSIONS.keys()),
    "platform": attr.string(mandatory = True, values = PLATFORMS.keys()),
}

def _dart_sdk_repo_impl(repository_ctx):
    version = repository_ctx.attr.dart_version
    platform = repository_ctx.attr.platform

    url = "https://storage.googleapis.com/dart-archive/channels/stable/release/{version}/sdk/dartsdk-{platform}-release.zip".format(
        version = version,
        platform = platform,
    )
    sha256 = TOOL_VERSIONS[version][platform]
    repository_ctx.download_and_extract(
        url = url,
        sha256 = sha256,
        stripPrefix = "dart-sdk",
    )

    # Determine the dart binary name based on platform
    if platform.startswith("windows"):
        dart_bin = "bin/dart.exe"
    else:
        dart_bin = "bin/dart"

    build_content = """# Generated by dart/repositories.bzl
load("@rules_dart//dart:toolchain.bzl", "dart_toolchain")

filegroup(
    name = "sdk_root",
    srcs = glob(["**"]),
    visibility = ["//visibility:public"],
)

dart_toolchain(
    name = "dart_toolchain",
    dart = "{dart_bin}",
    sdk_root = ":sdk_root",
    version = "{version}",
)
""".format(
        dart_bin = dart_bin,
        version = version,
    )

    repository_ctx.file("BUILD.bazel", build_content)

dart_repositories = repository_rule(
    _dart_sdk_repo_impl,
    doc = _DOC,
    attrs = _ATTRS,
)

def dart_register_toolchains(name, register = True, **kwargs):
    """Convenience macro for users which does typical setup.

    - create a repository for each built-in platform like "dart_linux_x64"
    - create a repository exposing toolchains for each platform like "dart_toolchains"
    - register a toolchain pointing at each platform
    Users can avoid this macro and do these steps themselves, if they want more control.

    Args:
        name: base name for all created repos, like "dart"
        register: whether to call through to native.register_toolchains.
            Should be True for WORKSPACE users, but false when used under bzlmod extension
        **kwargs: passed to each dart_repositories call
    """
    for platform in PLATFORMS.keys():
        dart_repositories(
            name = name + "_" + platform,
            platform = platform,
            **kwargs
        )
        if register:
            native.register_toolchains("@%s_toolchains//:%s_toolchain" % (name, platform))

    toolchains_repo(
        name = name + "_toolchains",
        user_repository_name = name,
    )
