"""Declare runtime dependencies

These are needed for local dev, and users must install them as well.
See https://docs.bazel.build/versions/main/skylark/deploying.html#dependencies
"""

load("//dart/private:toolchains_repo.bzl", "PLATFORMS", "toolchains_repo")
load("//dart/private:versions.bzl", "TOOL_VERSIONS")

########
# Remaining content of the file is only used to support toolchains.
########
_DOC = "Fetch the Dart SDK for a given version and platform"
_ATTRS = {
    "dart_version": attr.string(mandatory = True, values = TOOL_VERSIONS.keys()),
    "platform": attr.string(mandatory = True, values = PLATFORMS.keys()),
}

def _dart_sdk_repo_impl(repository_ctx):
    version = repository_ctx.attr.dart_version
    platform = repository_ctx.attr.platform

    url = "https://storage.googleapis.com/dart-archive/channels/stable/release/{version}/sdk/dartsdk-{platform}-release.zip".format(
        version = version,
        platform = platform,
    )
    sha256 = TOOL_VERSIONS[version][platform]
    repository_ctx.download_and_extract(
        url = url,
        sha256 = sha256,
        stripPrefix = "dart-sdk",
    )

    # Determine the dart binary name based on platform
    if platform.startswith("windows"):
        dart_bin = "bin/dart.exe"
    else:
        dart_bin = "bin/dart"

    build_content = """# Generated by dart/repositories.bzl
load("@rules_dart//dart:toolchain.bzl", "dart_toolchain")

filegroup(
    name = "sdk_root",
    srcs = glob(["**"]),
    visibility = ["//visibility:public"],
)

dart_toolchain(
    name = "dart_toolchain",
    dart = "{dart_bin}",
    sdk_root = ":sdk_root",
    version = "{version}",
)
""".format(
        dart_bin = dart_bin,
        version = version,
    )

    repository_ctx.file("BUILD.bazel", build_content)

dart_repositories = repository_rule(
    _dart_sdk_repo_impl,
    doc = _DOC,
    attrs = _ATTRS,
)

def dart_register_toolchains(name, register = True, **kwargs):
    """Convenience macro for users which does typical setup.

    - create a repository for each built-in platform like "dart_linux_x64"
    - create a repository exposing toolchains for each platform like "dart_toolchains"
    - register a toolchain pointing at each platform
    Users can avoid this macro and do these steps themselves, if they want more control.

    Args:
        name: base name for all created repos, like "dart"
        register: whether to call through to native.register_toolchains.
            Should be True when called directly, but False when used under bzlmod extension.
        **kwargs: passed to each dart_repositories call
    """
    for platform in PLATFORMS.keys():
        dart_repositories(
            name = name + "_" + platform,
            platform = platform,
            **kwargs
        )
        if register:
            native.register_toolchains("@%s_toolchains//:%s_toolchain" % (name, platform))

    toolchains_repo(
        name = name + "_toolchains",
        user_repository_name = name,
    )
