"""Declare runtime dependencies

These are needed for local dev, and users must install them as well.
See https://docs.bazel.build/versions/main/skylark/deploying.html#dependencies
"""

load("//dart/private:toolchains_repo.bzl", "CROSS_TARGETS", "PLATFORMS", "toolchains_repo")
load("//dart/private:versions.bzl", "TOOL_VERSIONS")

########
# Remaining content of the file is only used to support toolchains.
########
_DOC = "Fetch the Dart SDK for a given version and platform"
_ATTRS = {
    "dart_version": attr.string(
        doc = "The Dart SDK version to download (e.g. `3.11.0`). Must be a version listed in `versions.bzl`.",
        mandatory = True,
        values = TOOL_VERSIONS.keys(),
    ),
    "platform": attr.string(
        doc = "The target platform (e.g. `macos-arm64`, `linux-x64`). Must match a key in `PLATFORMS`.",
        mandatory = True,
        values = PLATFORMS.keys(),
    ),
}

def _dart_sdk_repo_impl(repository_ctx):
    version = repository_ctx.attr.dart_version
    platform = repository_ctx.attr.platform

    url = "https://storage.googleapis.com/dart-archive/channels/stable/release/{version}/sdk/dartsdk-{platform}-release.zip".format(
        version = version,
        platform = platform,
    )
    sha256 = TOOL_VERSIONS[version][platform]
    repository_ctx.download_and_extract(
        url = url,
        sha256 = sha256,
        stripPrefix = "dart-sdk",
    )

    # Determine the dart binary name based on platform
    if platform.startswith("windows"):
        dart_bin = "bin/dart.exe"
    else:
        dart_bin = "bin/dart"

    build_content = """# Generated by dart/repositories.bzl
load("@rules_dart//dart:toolchain.bzl", "dart_toolchain")

filegroup(
    name = "sdk_root",
    srcs = glob(["**"]),
    visibility = ["//visibility:public"],
)

dart_toolchain(
    name = "dart_toolchain",
    dart = "{dart_bin}",
    sdk_root = ":sdk_root",
    version = "{version}",
)
""".format(
        dart_bin = dart_bin,
        version = version,
    )

    # Generate cross-compilation toolchain targets for this SDK.
    cross_targets = CROSS_TARGETS.get(platform, [])
    for target_platform in cross_targets:
        target_meta = PLATFORMS[target_platform]
        build_content += """
dart_toolchain(
    name = "dart_toolchain_cross_{target_platform}",
    dart = "{dart_bin}",
    sdk_root = ":sdk_root",
    version = "{version}",
    target_os = "{target_os}",
    target_arch = "{target_arch}",
)
""".format(
            target_platform = target_platform,
            dart_bin = dart_bin,
            version = version,
            target_os = target_meta.dart_os,
            target_arch = target_meta.dart_arch,
        )

    repository_ctx.file("BUILD.bazel", build_content)

dart_repositories = repository_rule(
    _dart_sdk_repo_impl,
    doc = _DOC,
    attrs = _ATTRS,
)

def dart_register_toolchains(name, **kwargs):
    """Convenience macro for setting up Dart SDK repositories.

    - create a repository for each built-in platform like "dart_linux_x64"
    - create a repository exposing toolchains for each platform like "dart_toolchains"
    Users can avoid this macro and do these steps themselves, if they want more control.

    Args:
        name: base name for all created repos, like "dart"
        **kwargs: passed to each dart_repositories call
    """
    for platform in PLATFORMS.keys():
        dart_repositories(
            name = name + "_" + platform,
            platform = platform,
            **kwargs
        )

    toolchains_repo(
        name = name + "_toolchains",
        user_repository_name = name,
    )
