"""This module implements the Dart SDK toolchain rule."""

DartSdkInfo = provider(
    doc = "Information about the Dart SDK provided by the toolchain.",
    fields = {
        "dart": "File: The `dart` executable.",
        "sdk_root": "Target: The root directory of the SDK, containing `lib/` and `bin/`.",
        "version": "str: The SDK version string (e.g. `3.11.0`).",
        "tool_files": "list[File]: All files needed to run the SDK (for use in action inputs and runfiles).",
    },
)

def _dart_toolchain_impl(ctx):
    sdk_root = ctx.attr.sdk_root
    dart = ctx.attr.dart

    tool_files = ctx.attr.sdk_root.files.to_list()

    dart_sdk_info = DartSdkInfo(
        dart = ctx.file.dart,
        sdk_root = sdk_root,
        version = ctx.attr.version,
        tool_files = tool_files,
    )

    template_variables = platform_common.TemplateVariableInfo({
        "DART_BIN": ctx.file.dart.path,
    })
    default = DefaultInfo(
        files = depset(tool_files),
        runfiles = ctx.runfiles(files = tool_files),
    )

    toolchain_info = platform_common.ToolchainInfo(
        dart_sdk_info = dart_sdk_info,
        template_variables = template_variables,
        default = default,
    )
    return [
        default,
        toolchain_info,
        template_variables,
    ]

dart_toolchain = rule(
    implementation = _dart_toolchain_impl,
    attrs = {
        "dart": attr.label(
            doc = "The `dart` executable from the SDK's `bin/` directory.",
            mandatory = True,
            allow_single_file = True,
        ),
        "sdk_root": attr.label(
            doc = "A filegroup containing all SDK files. Used as action inputs when invoking the compiler.",
            mandatory = True,
        ),
        "version": attr.string(
            doc = "The SDK version string (e.g. `3.11.0`).",
            mandatory = True,
        ),
    },
    doc = "Defines a Dart SDK toolchain. Typically generated by the `dart_repositories` repository rule.",
)
