load("@gazelle//:def.bzl", "gazelle", "gazelle_binary")
load("@rules_dart//dart:defs.bzl", "dart_test")

gazelle_binary(
    name = "gazelle_bin",
    languages = [
        "@rules_dart//gazelle/dart",
    ],
)

gazelle(
    name = "gazelle",
    gazelle = "gazelle_bin",
)

_SAMPLES = [
    "bin/deferred_import.dart",
    "bin/hello.dart",
    "bin/show_import.dart",
    "lib/greeter.dart",
    "lib/io_impl.dart",
    "lib/platform_client.dart",
    "lib/stub.dart",
    "lib/web_impl.dart",
    "test/greeter_test.dart",
]

dart_test(
    name = "gazelle_test",
    size = "small",
    args = ["$(rlocationpath :gazelle_bin)"] +
           ["$(rlocationpath %s)" % f for f in _SAMPLES],
    data = _SAMPLES + [":gazelle_bin"],
    main = "gazelle_test.dart",
    deps = ["@rules_dart//dart/runfiles"],
)
