load(":codegen_test.bzl", "codegen_test_suite")
load(":common_test.bzl", "common_test_suite")
load(":dart_test_test.bzl", "dart_test_test_suite")
load(":language_version_test.bzl", "language_version_test_suite")
load(":library_test.bzl", "library_test_suite")
load(":native_assets_test.bzl", "native_assets_test_suite")
load(":semver_test.bzl", "semver_test_suite")
load(":versions_test.bzl", "versions_test_suite")
load(":yaml_parser_test.bzl", "yaml_parser_test_suite")

versions_test_suite(name = "versions_test")

common_test_suite(name = "common_test")

native_assets_test_suite(name = "native_assets_test")

yaml_parser_test_suite(name = "yaml_parser_test")

codegen_test_suite(name = "codegen_test")

dart_test_test_suite(name = "dart_test_test")

language_version_test_suite(name = "language_version_test")

library_test_suite(name = "library_test")

semver_test_suite(name = "semver_test")
