"""Unit tests for yaml_parser.bzl."""

load("@bazel_skylib//lib:unittest.bzl", "asserts", "unittest")
load("//dart/pub/private:yaml_parser.bzl", "parse_pubspec_deps", "parse_pubspec_lock")

_SAMPLE_LOCK = """\
# Generated by pub
# See https://dart.dev/tools/pub/glossary#lockfile
packages:
  collection:
    dependency: "direct main"
    description:
      name: collection
      sha256: abc123
      url: "https://pub.dev"
    source: hosted
    version: "1.18.0"
  meta:
    dependency: transitive
    description:
      name: meta
      sha256: def456
      url: "https://pub.dev"
    source: hosted
    version: "1.11.0"
  flutter:
    dependency: "direct main"
    description: flutter
    source: sdk
    version: "0.0.0"
sdks:
  dart: ">=3.0.0 <4.0.0"
"""

def _parse_lock_packages_test_impl(ctx):
    env = unittest.begin(ctx)
    result = parse_pubspec_lock(_SAMPLE_LOCK)
    asserts.equals(env, 3, len(result))
    asserts.true(env, "collection" in result)
    asserts.true(env, "meta" in result)
    asserts.true(env, "flutter" in result)
    return unittest.end(env)

def _parse_lock_hosted_test_impl(ctx):
    env = unittest.begin(ctx)
    result = parse_pubspec_lock(_SAMPLE_LOCK)
    collection = result["collection"]
    asserts.equals(env, "hosted", collection["source"])
    asserts.equals(env, "1.18.0", collection["version"])
    asserts.equals(env, "abc123", collection["description"]["sha256"])
    asserts.equals(env, "https://pub.dev", collection["description"]["url"])
    return unittest.end(env)

def _parse_lock_sdk_test_impl(ctx):
    env = unittest.begin(ctx)
    result = parse_pubspec_lock(_SAMPLE_LOCK)
    flutter = result["flutter"]
    asserts.equals(env, "sdk", flutter["source"])
    asserts.equals(env, "0.0.0", flutter["version"])
    return unittest.end(env)

_SAMPLE_PUBSPEC = """\
name: my_app
version: 1.0.0
environment:
  sdk: ">=3.0.0 <4.0.0"
dependencies:
  collection: ^1.18.0
  path: ^1.9.0
dev_dependencies:
  test: ^1.24.0
"""

def _parse_pubspec_deps_test_impl(ctx):
    env = unittest.begin(ctx)
    result = parse_pubspec_deps(_SAMPLE_PUBSPEC)
    asserts.equals(env, 2, len(result))
    asserts.true(env, "collection" in result)
    asserts.true(env, "path" in result)
    # dev_dependencies should NOT be included
    asserts.true(env, "test" not in result)
    return unittest.end(env)

def _parse_pubspec_deps_empty_test_impl(ctx):
    env = unittest.begin(ctx)
    result = parse_pubspec_deps("name: empty\n")
    asserts.equals(env, 0, len(result))
    return unittest.end(env)

_t0_test = unittest.make(_parse_lock_packages_test_impl)
_t1_test = unittest.make(_parse_lock_hosted_test_impl)
_t2_test = unittest.make(_parse_lock_sdk_test_impl)
_t3_test = unittest.make(_parse_pubspec_deps_test_impl)
_t4_test = unittest.make(_parse_pubspec_deps_empty_test_impl)

def yaml_parser_test_suite(name):
    unittest.suite(name, _t0_test, _t1_test, _t2_test, _t3_test, _t4_test)
