module(name = "pub_lock_cross_module_e2e")

bazel_dep(name = "rules_dart", version = "0.0.0")
local_path_override(
    module_name = "rules_dart",
    path = "../..",
)

bazel_dep(name = "module_b", version = "0.0.0")
local_path_override(
    module_name = "module_b",
    path = "module_b",
)

dart = use_extension("@rules_dart//dart:extensions.bzl", "dart")
dart.toolchain(dart_version = "3.11.4")
use_repo(dart, "dart_toolchains")

register_toolchains("@dart_toolchains//:all")

pub = use_extension("@rules_dart//dart/pub:extensions.bzl", "pub")
pub.from_lock(
    name = "deps_a",
    lock = "//:lock_a.lock",
)
use_repo(pub, "deps_a")
