load("//dart:defs.bzl", "dart_binary")

# Shim binary for the built_value Builder. SharedPartBuilder; produces
# .built_value.g.part shards.
dart_binary(
    name = "shim",
    srcs = ["shim.dart"],
    main = "shim.dart",
    visibility = ["//visibility:public"],
    deps = [
        "//dart/ext:builder_shim",
        "@ext_pub_deps//:built_value_generator",
    ],
)
