load("//dart:defs.bzl", "dart_binary")

# Shim binary for the json_serializable Builder. SharedPartBuilder; produces
# .<prefix>.g.part shards (combining to .g.dart happens in a separate step).
dart_binary(
    name = "shim",
    srcs = ["shim.dart"],
    main = "shim.dart",
    visibility = ["//visibility:public"],
    deps = [
        "//dart/ext:builder_shim",
        "@ext_pub_deps//:json_serializable",
    ],
)
